[project]
name = "cu-chinese-wiki-translations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepmerge>=2.0",
    "pyyaml>=6.0.3",
    "rich>=15.0.0",
]

[project.scripts]
merge-trans = "cu_chinese_wiki_translations.merge_data:main"
validate-data = "cu_chinese_wiki_translations.validate_data:main"

[build-system]
requires = ["uv_build>=0.11.19,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.17",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["TRY400","D400","D415","RUF001","S101"]  # RUF001:全角字符；

[tool.coverage.run]
relative_files = true
source = ["src/cu_chinese_wiki_translations"]
