# See https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
name: 构建翻译
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  merge-translations:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目
        uses: actions/checkout@v6.0.3
        with:
          submodules: true

      - name: 安装uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: 设置Python
        run: uv python install

      - name: 安装环境
        run: uv sync --locked --all-extras --dev

      - name: 验证数据格式正确
        run: uv run validate-data

      - name: 拉取最新官方翻译 
        run: git submodule update --init --recursive --remote

      - name: 合并翻译
        run: uv run merge-trans

      - name: 上传翻译
        uses: actions/upload-artifact@v7.0.1
        with:
          name: 维基简中
          path: 维基简中.json
          if-no-files-found: error
