# See https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
name: 构建翻译
on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  merge-translations:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目
        uses: actions/checkout@v6.0.3
        with:
          submodules: true

      - name: 安装uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: 设置Python
        run: uv python install

      - name: 安装环境
        run: uv sync --locked --all-extras --dev

      - name: 验证数据格式正确
        run: uv run validate-data

      - name: 拉取最新官方翻译 
        run: git submodule update --init --recursive --remote

      - name: 合并官方翻译
        run: uv run merge-trans

      - name: 合并软盘翻译
        run: uv run merge-trans -v 基准汉化_软盘.json -o wiki_translations_floppy.json 

      - name: 上传维基简中_基于官方翻译
        uses: actions/upload-artifact@v7.0.1
        with:
          name: 维基简中_基于官方翻译
          path: wiki_translations_official.json
          if-no-files-found: error

      - name: 上传维基简中_基于软盘翻译
        uses: actions/upload-artifact@v7.0.1
        with:
          name: 维基简中_基于软盘翻译
          path: wiki_translations_floppy.json
          if-no-files-found: error

      - name: 自动发布Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          preserve_order: true
          files: |
            wiki_translations_official.json
            wiki_translations_floppy.json
          generate_release_notes: true